apiVersion: v1
kind: Service
metadata:
  name: date-service
spec:
  selector:
    app: date-service
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-app
spec:
  selector:
    matchLabels:
      app: date-app
  replicas: 2
  template:
    metadata:
      labels:
        app: date-app
    spec:
      containers:
      - name: docker.io/tannifer/nodejs-image-demo
        image: docker.io/tannifer/nodejs-image-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080